### ISSUE TITLE
Vim very slow with .dart files

### ISSUE THREAD

**Issue by tjlaxs** [dart-lang/dart-vim-plugin#24] opened 2015-11-04 08:26 UTC
It seems like it is overwhelmed by something in this plugin. Is there any easy way to debug what causes it to get stuck for multiple seconds?

**Comment by cbracken** [comment] 2015-11-05 03:53
Do you have repro steps? Where are you seeing slowness?

**Comment by tjlaxs** [comment] 2015-11-05 10:38
Changing to the buffer with Dart file causes Vim to freeze for couple of seconds. And so does saving the Dart file.

**Comment by cbracken** [comment] 2015-11-05 17:45
I can't reproduce locally on vim 7.4.899. Tried three other machines with no slowdown seen either. Syntastic may well be the issue. IIRC it's backed by dartanalyzer and likely gets invoked on save. @polux has a set of patches to YouCompleteMe that runs against the analysis server instead and is much much faster. We're looking at getting those merged upstream.

**Comment by tjlaxs** [comment] 2015-11-05 17:52
Yeah, removing Syntastic makes this problem disappear.

**Comment by cbracken** [comment] 2015-11-05 17:55
Thanks for confirming. Closing the issue. It may be worth opening something against syntastic or dartanalyzer (performance). Once the YCM patches are landed, that's probably the way to go.

**Closed by cbracken** 2015-11-05 17:55 UTC

**Comment by hankchiutw** [comment] 2018-11-25 01:15
For someone may need this:
Add `let g:loaded_syntastic_dart_dartanalyzer_checker = 0` in `.vimrc` to skip dartanalyzer in syntastic.

**Comment by mwalkerwells** [comment] 2019-03-13 21:42
In there a way to address the performance issue other than disabling syntastic?

**Comment by natebosch** [comment] 2019-03-13 22:20
> In there a way to address the performance issue other than disabling syntastic?

Not likely - this is most likely a deficiency in the approach syntastic is taking to use the `dartanalyzer` cli (which is known to be too slow for interactive use) over using the analysis server.

FWIW our recommended approach for in editor linting is to use a LSP plugin (like https://github.com/natebosch/vim-lsc) and either [`dart_language_server`](https://github.com/natebosch/dart_language_server), or in upcoming versions of the SDK using the built in analysis server with `--lsp`. We're still working on the documentation for the latter.

**Comment by mwalkerwells** [comment] 2019-03-13 22:37
That's the setup I'm currently using, but the feedback from dart_language_server is pretty non-obvious. Was hoping for a decent workaround. :/

**Comment by natebosch** [comment] 2019-03-13 22:40
> but the feedback from dart_language_server is pretty non-obvious

How does it differ from syntastic? Which LSP client plugin are you using?

If you'd like to use syntastic specifically there isn't anything that can be done here to impact performance - you'd need to file an issue against their repo to ask them to change how they fetch errors.

**Comment by mwalkerwells** [comment] 2019-03-13 22:46
I'm pretty new to vim, so please excuse my ignorance. I'm using https://github.com/natebosch/vim-lsc and https://github.com/natebosch/dart_language_server & am super appreciative of your contributions. I'm not married to using syntastic—do you recommend an alternative?

**Comment by natebosch** [comment] 2019-03-13 22:49
That's the setup I recommend and use - and I get diagnostics in a way that I'm happy with.

Since I've never used syntastic I don't know how it compares specifically. If you let me know how the current setup is "non-obvious" I might be able to improve it.

I think syntastic uses the sign gutter to put symbols on the left of the editor - is that the main thing you miss from syntastic that you don't get when you only use vim-lsc? Is there anything else?

**Comment by mwalkerwells** [comment] 2019-03-13 23:04
**With Syntastic...**
![Screen Shot 2019-03-13 at 3 59 13 PM](https://user-images.githubusercontent.com/16157429/54320198-5fc44a80-45a9-11e9-844b-d89208e20219.png)

**Without Syntastic...** (No indication of error on line)
![Screen Shot 2019-03-13 at 4 01 31 PM](https://user-images.githubusercontent.com/16157429/54320196-5fc44a80-45a9-11e9-8b53-d3931cf5872d.png)

**Without Syntastic...** (Minimal indication of error with cursor on line)
![Screen Shot 2019-03-13 at 4 01 37 PM](https://user-images.githubusercontent.com/16157429/54320195-5fc44a80-45a9-11e9-8a96-9793ef3bbb3e.png)

**Comment by natebosch** [comment] 2019-03-13 23:22
I see 3 difference in the screenshots:

1. The location list is open on the "with syntastic". vim-lsc already populates the location list so it should have the same behavior as what you're used to with syntastic, you need to ":lopen" to see it. Maybe syntastic is doing that for you?
2. The highlighting for the error is different - underlined with syntastic and red with vim-lsc. You can configure either the `Error` highlight group, or the `lscDiagnosticError` (if you want to leave the default group alone) to change how it's highlighted. See `:help highlight`. It might take something like `highlight lscDiagnosticError term=underline` or maybe `highlight lscDiagnosticError cterm=underline`.
3. syntastic is using the sign gutter (the red `>>` on the left). vim-lsc doesn't have support for this today but I filed https://github.com/natebosch/vim-lsc/issues/165 to track as a feature request. I'm not sure how soon I'll be able to get to this. If its critical for you you might consider trying https://github.com/prabirshrestha/vim-lsp since they support signs AFAIK. I'm not sure whether they support the location list from the first point.

**Comment by mwalkerwells** [comment] 2019-03-14 18:35
Thanks for the detailed response—super helpful. Didn't know this information was available in the location list. My errors are actually correctly highlighted & while it would be nice, I don't care too much about the gutter.

Seriously, thank you—hope this all helps someone else too!
